// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClfuggMwS0bChxyt--3MIe163bfqJtH_o',
    appId: '1:128313531280:web:f5de27739565ec53983115',
    messagingSenderId: '128313531280',
    projectId: 'recetas-app-2025',
    authDomain: 'recetas-app-2025.firebaseapp.com',
    storageBucket: 'recetas-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgWg4wgQDo8OjKyofiq96Mp6jacH2SHY',
    appId: '1:128313531280:android:6975a181e832497b983115',
    messagingSenderId: '128313531280',
    projectId: 'recetas-app-2025',
    storageBucket: 'recetas-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIwSq2yUGl9wJcOv7rgL2bphNotPwf9k',
    appId: '1:128313531280:ios:3c85f243b64fff62983115',
    messagingSenderId: '128313531280',
    projectId: 'recetas-app-2025',
    storageBucket: 'recetas-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAIwSq2yUGl9wJcOv7rgL2bphNotPwf9k',
    appId: '1:128313531280:ios:3c85f243b64fff62983115',
    messagingSenderId: '128313531280',
    projectId: 'recetas-app-2025',
    storageBucket: 'recetas-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClfuggMwS0bChxyt--3MIe163bfqJtH_o',
    appId: '1:128313531280:web:a0646edc8d87f74a983115',
    messagingSenderId: '128313531280',
    projectId: 'recetas-app-2025',
    authDomain: 'recetas-app-2025.firebaseapp.com',
    storageBucket: 'recetas-app-2025.firebasestorage.app',
  );
}
